#!/usr/bin/env bash
#
# Pre-installation script for Mad SDK

set -o errexit
set -o pipefail
set -o nounset
#set -o xtrace

export MADSDK_ROOT=/Applications/madsdk

# Clean up any existing installation

rm -rf $MADSDK_ROOT
